import type { ClubItem } from "./types";

export const CLUBS_POPULAIRES: ClubItem[] = [
  { id: 86, name: "Real Madrid CF", shortName: "Real Madrid", crest: "https://crests.football-data.org/86.png", country: "Espagne" },
  { id: 81, name: "FC Barcelona", shortName: "Barça", crest: "https://crests.football-data.org/81.png", country: "Espagne" },
  { id: 524, name: "Paris Saint-Germain FC", shortName: "PSG", crest: "https://crests.football-data.org/524.png", country: "France" },
  { id: 65, name: "Manchester City FC", shortName: "Man City", crest: "https://crests.football-data.org/65.png", country: "Angleterre" },
  { id: 64, name: "Liverpool FC", shortName: "Liverpool", crest: "https://crests.football-data.org/64.png", country: "Angleterre" },
  { id: 5, name: "FC Bayern München", shortName: "Bayern", crest: "https://crests.football-data.org/5.svg", country: "Allemagne" },
  { id: 108, name: "FC Internazionale Milano", shortName: "Inter", crest: "https://crests.football-data.org/108.png", country: "Italie" },
  { id: 516, name: "Olympique de Marseille", shortName: "OM", crest: "https://crests.football-data.org/516.png", country: "France" },
  { id: 57, name: "Ajax Amsterdam", shortName: "Ajax", crest: "https://crests.football-data.org/57.png", country: "Pays-Bas" },
  { id: 110, name: "AS Roma", shortName: "Roma", crest: "https://crests.football-data.org/110.png", country: "Italie" },
  { id: 529, name: "Borussia Dortmund", shortName: "Dortmund", crest: "https://crests.football-data.org/529.png", country: "Allemagne" },
  { id: 61, name: "Chelsea FC", shortName: "Chelsea", crest: "https://crests.football-data.org/61.png", country: "Angleterre" },
  { id: 66, name: "Manchester United FC", shortName: "Man Utd", crest: "https://crests.football-data.org/66.png", country: "Angleterre" },
  { id: 503, name: "Atlético de Madrid", shortName: "Atlético", crest: "https://crests.football-data.org/503.png", country: "Espagne" },
  { id: 103, name: "Benfica", shortName: "Benfica", crest: "https://crests.football-data.org/103.png", country: "Portugal" },
  { id: 109, name: "Juventus FC", shortName: "Juventus", crest: "https://crests.football-data.org/109.png", country: "Italie" },
  { id: 102, name: "AFC Ajax", shortName: "Ajax", crest: "https://crests.football-data.org/102.png", country: "Pays-Bas" },
  { id: 78, name: "Club Atlético de Madrid", shortName: "Atleti", crest: "https://crests.football-data.org/78.png", country: "Espagne" },
  { id: 90, name: "Stuttgart", shortName: "Stuttgart", crest: "https://crests.football-data.org/90.png", country: "Allemagne" },
  { id: 523, name: "Olympiacos CFP", shortName: "Olympiacos", crest: "https://crests.football-data.org/523.png", country: "Grèce" },
  { id: 173, name: "FC Porto", shortName: "Porto", crest: "https://crests.football-data.org/503.png", country: "Portugal" },
  { id: 500, name: "Bologna FC 1909", shortName: "Bologna", crest: "https://media.api-sports.io/football/teams/500.png", country: "Italie" },
  { id: 114, name: "Napoli", shortName: "Napoli", crest: "https://crests.football-data.org/114.png", country: "Italie" },
  { id: 563, name: "PSV Eindhoven", shortName: "PSV", crest: "https://crests.football-data.org/563.png", country: "Pays-Bas" },
];